# Create and start:
#   docker compose up -d

# View running:
#   docker ps
# View running and stopped:
#   docker ps --all
# Start the stopped container (e.g. after host reboot):
#   docker start mysql8

# https://docs.docker.com/reference/cli/docker/compose/logs/
# View logs per container Or service
#   docker logs mysql8
#   docker logs mongo
# Or
#   docker compose logs mongodb

# Stop:
#   docker compose down -v
# Wipe volume (in case you forgot -v):
#   docker volume rm mysql8data
name: p2
services:
  mysql8:
    image: mysql:8.4-oraclelinux9
    container_name: mysql8
    volumes:
      - mysql8data:/var/lib/mysql
    networks:
      - sTest
    hostname: mysql8
    ports:
      - 3306:3306
    environment:
      MYSQL_HOST_NAME: mysql8
      MYSQL_DATABASE: 'inventory'
      MYSQL_ROOT_PASSWORD: '999'
      MYSQL_USER: 'shsha'
      MYSQL_PASSWORD: '999'

  mongodb:
    image: mongo:8.0.8-noble
    container_name: mongo
    volumes:
      - mongo8data:/data/db
      # import once on DB init
      - ./reviews-lines.json:/docker-entrypoint-initdb.d/reviews.json
    networks:
      - sTest
    hostname: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 'simple-1'
      MONGO_INITDB_DATABASE: reviews

networks:
  sTest:
    name: d-net1
    driver: bridge
volumes:
  mysql8data:
  mongo8data:
